

spring:
#  mvc:
#    throw-exception-if-no-handler-found: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
#  web:
#    resources:
#      add-mappings: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(Au3SL+m/4RSF2Min2FbtgL1AXmtaTNCTyx8JqB7VYRhJS0J6AYmmMuHuQGdHDNmDReH4OGtaPAEdIldFVWE8WXwpemieKqg/WY/Q5rlhI4Y=)
    username: ENC(IqYxVsUYmtyLlBQyq7SsTke2+sUA+XLOvM2GlDue1+xqWcDxBNlLs9XpFkoXZa5C)
    password: ENC(GAZhFF/NgFXPGyAGPVnB4o7b05K7YRRff+WtNzTAbiH5Q/+Eb/LOWsEkMh2c/x3a)
  jpa:
    hibernate:
      ddl-auto: none
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        highlight_sql: true
#  logging:
#    level:
#      org.hibernate.SQL: debug
#      org.hibernate.orm.jdbc.bind: trace
  jwt:
    secret: ENC(jMiFO/13IhP75q42bQc5+ZOXjW9WntB7t9zxJbJu5wwRYYQyREfUV5AVUNRJksynM1tT8dJTXJjGbNZ1z4OVOUjYbch0U9SrXssTCgYy6YgVdJido/SeZYDnk1f/Bts2vPP18M2vu+dZ2HPhyqESSQ==)
    access-timeout: 30
    refresh-timeout: 60
  mail:
    host: smtp.gmail.com
    port: 465
    username: ENC(MgH4/vWwpi4JuijbFa/CybfAWiObYAezjPio/P0AP77CFWaNibtk/Hyy7yRyJGgHgBDFGkE8QMPFF8+FJSXjHw==)
    password: ENC(asSDHG8snHlNweGYafNee/WhubYfoUvNBV2LLLybMX6iQP9VtQOXfrH4PUH71+ca1+KkCj0aE3WCZVNS2XqYYQ==)
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
    protocol: smtps
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 50
    redis:
      host: localhost
      port: 6379
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-name: google
#            client-id: ENC(oDOwWTikjKRZ6OQxf90DC0s1TapdQg0Y8iK8Jcr2noRvBFyjrexDBN50eEPR+ae7CWycZSF8nkKOgjuLTokyRFuJmi1X/i54vAE8sskEeVsWR25+F7Z8N0DvhBpEpCZItqsCoJjDVDL1EwVI3+ZFMg==)
#            client-secret: ENC(6o3Xbsafg92CpjHOetB9FhSWn60Psn8/lUko873VP3Qvuk7gqEQlkKa8iUPIbnUgrnI0BGvuxnfUIPIZnI0GfHg8R0zBJvVRboZwHfXyOrM=)
#            redirect-uri: http://localhost:8090/login/oauth2/code/google
#            authorization-grant-type: authorization_code
#            scope: profile, email
#          naver:
#            client-name: naver
#            client-id: ENC(pp/BVgjQUM8v+UzhpIKzGGAs76krqDrct2afdVM8IMl2ZgZtXF0puumGZz8M45BmYfZjdwQ6jSrexDRTI1VYQg==)
#            client-secret: ENC(JaKrMzWPNb/BPRKbQzWMp8RWhLmdCJL51oqQpmyAzZfJSGyES+BIe8gyaZMD/UiJ)
#            redirect-uri: http://localhost:8090/login/oauth2/code/naver
#            authorization-grant-type: authorization_code
#            scope: name, email, nickname
#        provider:
#          naver:
#            authorization-uri: https://nid.naver.com/oauth2.0/authorize
#            token-uri: https://nid.naver.com/oauth2.0/token
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            user-name-attribute: response

jasypt:
  encryptor:
    password: side-anything
server:
  port: 8090
#  error:
#    whitelabel:
#      enabled: false  # ?? ?? ? Spring ?? ?? ??? ?? ??

social:
  naver:
    client:
      id: ENC(pp/BVgjQUM8v+UzhpIKzGGAs76krqDrct2afdVM8IMl2ZgZtXF0puumGZz8M45BmYfZjdwQ6jSrexDRTI1VYQg==)
      secret: ENC(JaKrMzWPNb/BPRKbQzWMp8RWhLmdCJL51oqQpmyAzZfJSGyES+BIe8gyaZMD/UiJ)
  google:
    client:
      id: ENC(oDOwWTikjKRZ6OQxf90DC0s1TapdQg0Y8iK8Jcr2noRvBFyjrexDBN50eEPR+ae7CWycZSF8nkKOgjuLTokyRFuJmi1X/i54vAE8sskEeVsWR25+F7Z8N0DvhBpEpCZItqsCoJjDVDL1EwVI3+ZFMg==)
      secret: ENC(6o3Xbsafg92CpjHOetB9FhSWn60Psn8/lUko873VP3Qvuk7gqEQlkKa8iUPIbnUgrnI0BGvuxnfUIPIZnI0GfHg8R0zBJvVRboZwHfXyOrM=)

