

spring:
#  mvc:
#    throw-exception-if-no-handler-found: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
#  web:
#    resources:
#      add-mappings: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(ODID0iGF4zFRZZQWeVvVR23yREpNeyASaineqkE/ZKDMFC6KdoOcEE7leXBYcb8EvOjJHgIOlXiH/RqrFNKKDjlDEE514IDK2iMEXMNYmVQ=)
    username: ENC(nP2RJiOCNvsBOFUY7RCf75IsQt+cY8RPQ21yhs+Cj28R6w3u+j8+dbt77LTuPfOb)
    password: ENC(VrxASLM90/dPpu+HnwcfLploD/YDqzY1/jx79b/Ua/Hu+Pj65nQP8v5+7jlGn+na)
  jpa:
    hibernate:
      ddl-auto: none
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        highlight_sql: true
#  logging:
#    level:
#      org.hibernate.SQL: debug
#      org.hibernate.orm.jdbc.bind: trace
  jwt:
    secret: ENC(jMiFO/13IhP75q42bQc5+ZOXjW9WntB7t9zxJbJu5wwRYYQyREfUV5AVUNRJksynM1tT8dJTXJjGbNZ1z4OVOUjYbch0U9SrXssTCgYy6YgVdJido/SeZYDnk1f/Bts2vPP18M2vu+dZ2HPhyqESSQ==)
    access-timeout: 30
    refresh-timeout: 60
  mail:
    host: smtp.gmail.com
    port: 465
    username: ENC(MgH4/vWwpi4JuijbFa/CybfAWiObYAezjPio/P0AP77CFWaNibtk/Hyy7yRyJGgHgBDFGkE8QMPFF8+FJSXjHw==)
    password: ENC(asSDHG8snHlNweGYafNee/WhubYfoUvNBV2LLLybMX6iQP9VtQOXfrH4PUH71+ca1+KkCj0aE3WCZVNS2XqYYQ==)
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
    protocol: smtps

jasypt:
  encryptor:
    password: side-anything
#server:
#  error:
#    whitelabel:
#      enabled: false  # ?? ?? ? Spring ?? ?? ??? ?? ??

